[global]
error_log = /dev/stderr
daemonize = no

[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
pm = static
pm.max_children = 10
pm.max_requests = 1000
request_terminate_timeout = 60s
